import type { Content } from "./features/content/types"

const dummyUser01Contents: Content[] = [
  ...[...Array(8)].map((_, i) => ({
    id: String(i + 1),
    title: `投稿物タイトル0${String(i + 1)}`,
    creator: "投稿者名01",
    thumbnail: "/images/500x300.png",
    nftImage: "/images/nft.png",
    views: 50,
    likes: 5,
    receivedPOL: 31,
    isPublic: false,
    tags: ["冒険", "アニメ"],
  })),
]

export const dummyContents: Content[] = [
  ...dummyUser01Contents,
  {
    id: "9",
    title: "投稿物タイトル09",
    creator: "投稿者名02",
    thumbnail: "/images/500x300.png",
    nftImage: "/images/nft.png",
    views: 20,
    likes: 4,
    receivedPOL: 31,
    isPublic: false,
    tags: ["冒険", "アニメ"],
  },
  {
    id: "10",
    title: "投稿物タイトル10",
    creator: "投稿者名03",
    thumbnail: "/images/500x300.png",
    nftImage: "/images/nft.png",
    views: 30,
    likes: 300,
    receivedPOL: 31,
    isPublic: false,
    tags: ["冒険", "アニメ"],
  },
  {
    id: "11",
    title: "投稿物タイトル11",
    creator: "投稿者名04",
    thumbnail: "/images/500x300.png",
    nftImage: "/images/nft.png",
    views: 30,
    likes: 300,
    receivedPOL: 31,
    isPublic: false,
    tags: ["冒険", "アニメ"],
  },
  {
    id: "12",
    title: "投稿物タイトル12",
    creator: "投稿者名05",
    thumbnail: "/images/500x300.png",
    nftImage: "/images/nft.png",
    views: 50,
    likes: 5,
    receivedPOL: 31,
    isPublic: false,
    tags: ["冒険", "アニメ"],
  },
]

export const dummyHistories = [
  {
    itemId: "1",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "10/09 12:03",
    content: "100いいねをしました！",
    creator: "クリエイター名",
  },
  {
    itemId: "6",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "10/09 16:03",
    content: "500いいねをしました！",
    creator: "クリエイター名",
  },
  {
    itemId: "2",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "10/10 12:02",
    content: "あなたが応援した〜が〜を達成しました！",
    creator: "クリエイター名",
  },
  {
    itemId: "2",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "10/11 12:01",
    content: "達成NFTを獲得しました！",
    creator: "クリエイター名",
  },
  {
    itemId: "5",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "12/01 12:03",
    content: "NFTを獲得しました！",
    creator: "クリエイター名",
  },
  {
    itemId: "3",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "12/05 12:03",
    content: "NFTを獲得しました！",
    creator: "クリエイター名",
  },
  {
    itemId: "4",
    itemTitle: "投稿作品タイトル",
    creatorId: "1",
    itemImage: "/images/activity.png",
    createdAt: "12/29 12:03",
    content: "NFTを獲得しました！",
    creator: "クリエイター名",
  },
]
